basePath: /api/v1
definitions:
  handlers.RegisterUserRequest:
    properties:
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      isAdmin:
        type: boolean
      last_name:
        type: string
      password:
        type: string
      user_name:
        type: string
    type: object
  handlers.RegisterUserResponse:
    properties:
      error:
        type: string
      id:
        type: integer
      message:
        type: string
    type: object
  handlers.UserLoginRequest:
    properties:
      password:
        type: string
      user_name:
        type: string
    type: object
  handlers.UserLoginResponse:
    properties:
      error:
        type: string
      message:
        type: string
      token:
        type: string
    type: object
host: localhost:5000
info:
  contact:
    email: ramsureka007@gmail.com
    name: Utsav Sureka
    url: utsav.sureka@stl.tech
  description: API for Online Marketplace having several functionality to handle user,product
    and order details.
  title: Documenting API (Online Marketplace Apis)
  version: "2.0"
paths:
  /user/login:
    post:
      consumes:
      - application/json
      description: login and generate jwt token
      parameters:
      - description: login request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.UserLoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.UserLoginResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.UserLoginResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.UserLoginResponse'
      summary: login a user
      tags:
      - users
  /user/register:
    post:
      consumes:
      - application/json
      description: Register a new user and add the details in the database
      parameters:
      - description: User registration request
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/handlers.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handlers.RegisterUserResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/handlers.RegisterUserResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/handlers.RegisterUserResponse'
      summary: Register a new user
      tags:
      - users
swagger: "2.0"
